server:
  port: 8080

spring:
  banner:
    location: classpath:banner.txt
  datasource:
    username: root
    password: PASSWORD
    url: jdbc:mysql://localhost:3306/PigeonDAL?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQuery=true

mybatis:
  ###### ###### ###### ###### ###### ###### ###### ###### ###### ###### ###### ######
  ### DO NOT ADD THE FOLLOWING LINE, OR ELSE @Bean SqlSessionFactory cannot be created
  ###### ###### ###### ###### ###### ###### ###### ###### ###### ###### ###### ######
  mapper-locations: claspath:mybatis/mapping/*.xml
  type-aliases-package: pigeon.backend.pigeondalback.entity
  config-location: classpath:mybatis/mybatis-config.xml

#showLogs
logging:
  level:
    com:
      johannes:
        wassupforum:
          mapper : debug
  file:
    name: log/log-dev.log


#redis:
#  host: 127.0.0.1
#  port: 6379
#  timeout: 10
#  poolMaxTotal: 1000
#  poolMaxIdle: 500
#  poolMaxWait: 500
#
## config snowflake
#snowflake:
#  machineId: 1
#  dataCenterId: 1
